DROP TABLE IF EXISTS player_info;

CREATE TABLE player_info (
    playerid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    graddate INTEGER NOT NULL,
    position TEXT NOT NULL,
    batthrow TEXT NOT NULL,
    date DATE NOT NULL DEFAULT NOW(),
    phone TEXT ,
    url TEXT ,
    dash INTEGER , 
    platefirst INTEGER ,
    turntime INTEGER ,
    exitvelo INTEGER ,
    poptime INTEGER ,
    notes TEXT 
);

ALTER TABLE player_info
 ADD COLUMN
 schoolId INTEGER REFERENCES schools(id)
 ON DELETE CASCADE NOT NULL
 ;

 INSERT INTO player_info (playerid, name, graddate, position, batthrow, phone, url, dash, platefirst, turntime, exitvelo, poptime, notes, schoolId)
 values
    (1, 'Babe Ruth', 1913, 'Center Field', 'Bat', '9725555555', 
    'https://www.youtube.com/watch?v=7WfVREOHaAk', 1, 1, 1, 1, 1, 'Babe Ruth', 1);

